- objects/obj_controller/Mouse_50.gml
- objects/obj_popup/Mouse_50.gml
- scripts/scr_weapons_equip/scr_weapons_equip.gml
All vehicles can now be reequipped, although the double-weapon bug currently prevents rhinos being modified.
Equip script now checks the unit type for lists of valid equipment under more circumstances. Dreadnoughts should now only ever see dreadnought gear, predators see pred gear etc. Some vehicles have different weapon slots between slot 1 and slot 2 to differentiate between turrets and sponsons.
> Adding vehicle reequipping and reworked equipping script

- objects/obj_mass_equip/Step_0.gml
- objects/obj_shop/Create_0.gml
- scripts/scr_add_man/scr_add_man.gml
- scripts/scr_battle_roster/scr_battle_roster.gml
- scripts/scr_initialize_custom/scr_initialize_custom.gml
- scripts/scr_ui_display_weapons/scr_ui_display_weapons.gml
- scripts/scr_ui_formation_bars/scr_ui_formation_bars.gml
- scripts/scr_ui_manage/scr_ui_manage.gml
- scripts/scr_vehicle_count/scr_vehicle_count.gml
- renamed remaining 'armor' instances to 'armour', which also fixed a CTD
- fixed vehicle count + armamentarium CTDs (forgot to rename 1 old var)
- fixed adjust formation CTDs
- removed Heavy Conversion Beamers and Void Shields from Armour tab in shop (still visible in Vehicles tab)
- beautified obj_chop/Create_0
- fixed CTD on mass equip
ready for review and merge
> fixes for multiple CTDs

- scripts/scr_vehicle_count/scr_vehicle_count.gml
- Vehicles Tab in armamentorium Crashes on turn 1 when clicking it
> Fix: crash on turn 1 in armamentorium vehicle tab

- scripts/scr_restart_variables/scr_restart_variables.gml
fixes or at the least greatly reduces frequency of the restart variable crash (did 25 game starts with no crashes)
- ok so does not fully eradicate but greatly reduces instances will try adding some error handling maybe
> fix restart variable crash

- objects/obj_controller/Mouse_50.gml
- scripts/macros/macros.gml
- scripts/scr_add_stc_fragment/scr_add_stc_fragment.gml
fixes #219 
Cause: STC Identification code missing limit check.
Fix: Implement bounds check - 6 per category (wargear/vehicles/ships) at present. As defined by MAX_STC_PER_SUBCATEGORY
Does not fix: 'Identify' button remaining highlighted if limit has been reached
Additional changes/Side effects: STC in the category with least identified STCs (wargear/vehicles/ships) will be identified first.
Was: Purely random before
> Fix overspending stc fragments

- objects/obj_shop/Create_0.gml
This pull request removes the duplicate assault cannon entry in the armamentarium.
I kept the lower price; the commit history wasn't clear to me which prices were intended.
> fix: removed duplicate assault cannon in shop for dreadnoughts.

- objects/obj_controller/Create_0.gml
- objects/obj_controller/KeyPress_32.gml
- objects/obj_popup/Mouse_51.gml
- scripts/scr_load/scr_load.gml
- scripts/scr_save/scr_save.gml
- scripts/scr_zoom/scr_zoom.gml
Changes
1. zoom logic was duplicated and is now centralized in `src_zoom`, for maintainability.
2. refactor zoom logic to use `else`
3. `was_zoomed` was removed after the above refactor, as it was then never read.
4. replaced `__view_set` with the API `view_set_visible` for more direct view management.
The saves I made before removing `was_zoomed` still load after.
> refactor: zoom and remove redundant was_zoomed

- ChapterMaster.resource_order
- ChapterMaster.yyp
- objects/obj_en_fleet/Alarm_1.gml
- objects/obj_ncombat/Alarm_5.gml
- scripts/scr_apothecary_ground/scr_apothecary_ground.gml
- scripts/scr_cheatcode/scr_cheatcode.gml
- scripts/scr_crusade/scr_crusade.gml
- scripts/scr_marine_struct/scr_marine_struct.gml
- scripts/scr_necron_tombs/scr_necron_tombs.gml
- scripts/scr_necron_tombs/scr_necron_tombs.yy
- scripts/scr_planetary_feature/scr_planetary_feature.gml
- scripts/scr_random_event/scr_random_event.gml
- scripts/scr_return_ship/scr_return_ship.gml
a few minor bug fixes
- in obj_en_fleet/Alarm1  a variable not being checked for noone value resulting in crash
- necron tombs not displaying the correct name after being sealed or awakening
- excess number of marines sometimes dying in crusades
- also a general refactor of crusades script
- refactored crusade event into a function so it can be activated more readily and cleans up event script
- minor feature in a report of heroic deeds from crusades (logs new traits added to marines)
- added cheat/debug for crusading
to test and to launch crusades at will enter "eventcrusade" into the cheat console and then check the event log to see where the crusade event launched send fleet and end turn until crusade fleet returns
> crusade bug fix, and improvements

- objects/obj_controller/Alarm_5.gml
- objects/obj_controller/Mouse_50.gml
- objects/obj_event/Step_0.gml
- objects/obj_ncombat/Alarm_7.gml
- objects/obj_p_assra/Alarm_0.gml
- objects/obj_pnunit/Alarm_6.gml
- objects/obj_popup/Mouse_50.gml
- objects/obj_popup/Step_0.gml
- objects/obj_temp4/Alarm_2.gml
- objects/obj_temp4/Alarm_3.gml
- objects/obj_temp4/Alarm_4.gml
- objects/obj_temp4/Alarm_5.gml
- scripts/scr_add_corruption/scr_add_corruption.gml
- scripts/scr_add_man/scr_add_man.gml
- scripts/scr_civil_roster/scr_civil_roster.gml
- scripts/scr_company_order/scr_company_order.gml
- scripts/scr_dead_marines/scr_dead_marines.gml
- scripts/scr_dialogue/scr_dialogue.gml
- scripts/scr_enemy_ai_d/scr_enemy_ai_d.gml
- scripts/scr_event_dudes/scr_event_dudes.gml
- scripts/scr_event_gossip/scr_event_gossip.gml
- scripts/scr_initialize_custom/scr_initialize_custom.gml
- scripts/scr_kill_unit/scr_kill_unit.gml
- scripts/scr_load/scr_load.gml
- scripts/scr_marine_struct/scr_marine_struct.gml
- scripts/scr_max_marine/scr_max_marine.gml
- scripts/scr_move_unit_info/scr_move_unit_info.gml
- scripts/scr_powers/scr_powers.gml
- scripts/scr_save/scr_save.gml
- scripts/scr_ui_advisors/scr_ui_advisors.gml
- Stops the CTD from the chaos emissary
- deprecates the use of obj_ini.chaos[company][unit] for unit.corruption
- this is ultimately laying the way to implementing corruption properly in the near future
- finishes all of the khorne options in the emissary allowing the you to make a sacrifice and in return receive khornes favour/attention (currently a trait called blood_for_blood)
> corruption change and emissary bug

- scripts/scr_complex_colour_kit/scr_complex_colour_kit.gml
- scripts/scr_draw_unit_image/scr_draw_unit_image.gml
- make sure temporary sprites are explicitly deleted when drawing components
- fix missing head on creation screen complex sprite
- previous component replacement method would leave sprites in memory and cause memory leaks @EttyKitty  merged your method and mine to hopefully make safe method, feel free to change method names though
-
> refactor: Memory safe drawing of components

- scripts/scr_initialize_custom/scr_initialize_custom.gml
- Removes duplicated Tactical Marine code in `Lightning Warriors` if statement.
- Having both `Ambushers` and `Lightning Warriors` would crash the game on start.
- https://discord.com/channels/714022226810372107/1333399348268109905
> fix: `Ambushers`+`Lightning Warriors` crash

- scripts/scr_system_spawn_functions/scr_system_spawn_functions.gml
- Changes if statement in the `set_player_recruit_planet` function to check for homeworld and separate recruiting star, and copies homeworld star name generation code in a else statement.
- Fleet-based Chapters mixed up Homeworld and Recruiting world names causing troops to end up in a non-existent star.
- https://discord.com/channels/714022226810372107/1333788875981852743
> fix: Homeworld and recruiting world names mixing up

- scripts/scr_specialist_point_handler/scr_specialist_point_handler.gml
- Move variable into scope.
- Variable is initialized in a different scope/function from where it is called, causing `not set before reading it` errors when called.
- https://discord.com/channels/714022226810372107/1337069225042251847
> fix: Tech Heresy detection var in wrong scope

- scripts/scr_PlanetData/scr_PlanetData.gml
- Make influence and corruption reset to zero when population is zero.
- So players don't spend 30+ turns purging on a planet with no population and 20+ turns dealing with Traitors and/or Tau spawning and contesting the planet.
- Adds merit to https://github.com/Adeptus-Dominus/ChapterMaster/pull/467 bombard flavor text.
> feat: if population equals zero then reset all influence

- scripts/scr_bomb_world/scr_bomb_world.gml
- scripts/scr_purge_world/scr_purge_world.gml
- Make it more obvious that purging lowers Tyranid influence, when it doesn't and add some flavor text.
- Players get confused if purging actually does anything.
- https://discord.com/channels/714022226810372107/714023282780799028/1336280298438000680
> feat: Make Purge interaction with Cults more obvious

- scripts/scr_get_item_names/scr_get_item_names.gml
- Adds the missing option to add HK missiles after being initialized.
- It was only initialized before but you could not arm them.
-
> fix: Rhino missing HK missile armament

- scripts/scr_PlanetData/scr_PlanetData.gml
- scripts/scr_garrison/scr_garrison.gml
- Add some debug code and another disposition chart item, disallow garrisons from making disposition going into the negatives and flip a comparison.
- Garrisons could make relations go into the negative which could take forever to get out and with the incorrect comparison direction would take away relations if the charsima check failed and relations with the faction owner was higher.
> fix: Garrison fixes and minor changes

- objects/obj_p_assra/Step_0.gml
- Replace `repeat` for a `for` loop.
- Out of range crash.
- https://discord.com/channels/714022226810372107/1340346439531888650
> fix: Boarders experience out of range

- scripts/scr_PlanetData/scr_PlanetData.gml
- scripts/scr_garrison/scr_garrison.gml
- Corrected inverted comparison and incorrect value, remove conflicting comparison and some debug info to show disposition value.
- When failing charisma check it added 100 points due to a inverted comparison and incorrect value, and the conflicting comparison prevented charisma check.
> fix: More debug and more fixes for garrisons

- scripts/scr_recruit_data/scr_recruit_data.gml
- Add `find_recruit_corruption(planet_type)` function, similar to `find_recruit_success_chance()`. This thing returns the corruption value of a recruit, based on the selected trial and their source planet type, passed through a Gaussian distribution.
- Remove planet types from corruption bonuses in trials, and move them to the above function (so that they are independent of trials).
- Change trial corruption bonus to the `[base, sd]` format, for Gaussian distribution in `find_recruit_corruption()`.
- Add a small corruption bonus to "Survival of the Fittest" (I think it fits?) and "Combat Challenge"; and a small malus to "Knowledge of self" and "Shrine" planets. (for detailed changes, see the file itself)
- I love Gaussian distribution and I don't love static numbers or flat distribution. …
> feat: Planets affect recruit corruption and it's gaussian random

- scripts/scr_roster/scr_roster.gml
- After certain turns, your ship may not be able to be selected in the raid/attack/purge, thus you can not start your attack by these method, but only load and unload repeatly
- bug report issue found by user
- https://discord.com/channels/714022226810372107/1340995217871999046
> fix: index error with roster causing raid/purge issues

- objects/obj_bomb_select/Alarm_1.gml
- scripts/scr_player_fleet_functions/scr_player_fleet_functions.gml
- scripts/scr_player_ship_functions/scr_player_ship_functions.gml
- make obj_bomb use variable array lengths in lione with player ship updates
- make functions to determine ship and fleets bombard scores
- make bombard capabilities logged to ship weapons as opposed to ablative
- this means in the furture bombard capabilities of ships can be upgradable or degradeable
- in response to bug report
- https://discord.com/channels/714022226810372107/1120687959365128243
> fix: Refactor obj_bomb alarm 1 array length bug

- scripts/scr_ruins_reward/scr_ruins_reward.gml
- use modern fleet array methods to determine id of nearest ship to load ruins expedition rewards
-
- https://discord.com/channels/714022226810372107/1120687959365128243/threads/1338971523402305588
> fix: Crash from old ship array methods

- objects/obj_p_assra/Step_0.gml
Units with higher damage resistance used to take higher damage.
Corrected damage calculation logic to properly handle damage resistance.
> fix: Damage taken when boarding

- scripts/scr_initialize_custom/scr_initialize_custom.gml
Fix sternguard veterans spawning with two melee weapons, due to the overburden protection.
Add a heavy weapon pack to the heavy weapon sternguard loadout.
None
New game as ultramarines, two melee weapons are no more.
None
None
> fix: Sternguard Veterans with two melee weapons

- datafiles/main/chapters/9.JSON
Fix the Raven Guard chapter master having two jetpacks.
Remove the jetpack from the gear slot in the chapter's json file.
None
New game as RG, no double jetpacks.
https://discord.com/channels/714022226810372107/1346752447242043413
None
> fix: Double jetpack on the RG CM

- objects/obj_controller/Alarm_5.gml
- objects/obj_controller/Mouse_50.gml
- scripts/scr_controller_helpers/scr_controller_helpers.gml
Reclusium actually works beyond first 11 marines.
Actually check against arrays in the array, should also have fixed marines disappearing in the Reclusium and marines above 250 don't disappear.
Renaming god.
Load game, jail 500 marines in a company.
> fix: Reclusium goes beyond 11

- objects/obj_enunit/Alarm_1.gml
- objects/obj_shop/Create_0.gml
- scripts/scr_flavor/scr_flavor.gml
- scripts/scr_marine_struct/scr_marine_struct.gml
- scripts/scr_player_combat_weapon_stacks/scr_player_combat_weapon_stacks.gml
- scripts/scr_weapon/scr_weapon.gml
- Make assaults more useful (or not a useless meat farm, in other words).
- Give 2 range to the hammer of wrath jump pack attack, allowing it to attack from behind a friendly column.
- Change the damage from being a stat formula, to just using the melee attack of the marine. Debatable whenever there should be some kind of buff.
- Rename the weapon from "hammer_of_wrath" to "Hammer of Wrath".
- Add the Hammer of Wrath special property into the jetpack tooltip.
- Create a second profile for the jump pack
- Both HoW profiles use primary melee weapon spli, max kills.
- Ranged profile has a 25% melee attack reduction, full melee has a 25% increase.
- Ranged profile has 6 ammo, melee has 8.
Item balance:
- Remove the HP mod from the Jump Pack and the Iron Halo (doesn't make sense).
- Increase …
> feat: Jump packs give a ranged melee attack

- scripts/scr_creation/scr_creation.gml
- In the original formulas, cooperation slider was not very good imo, both if you scroll it down or up. Free 10 points.
- Disposition was only affected by the purity, when stability also means mutated marines, even worse, actually.
- Strength was only reducing disposition when above 5, not increasing when below. A bit weird.
- Each point of cooperation now gives/takes 4 disposition with all factions, except inquisition and mechanicus. They get 2 per point.
- Each point of purity below 10 reduces disposition with inquisition by 2, with ecclesiarchy by 1.
- Each point of stability below 10 reduces disposition with inquisition by 2, with ecclesiarchy by 1.
- Each point of strength below 5 now increases imperium disposition by 2.
- Daemon Binders now also reduces the church dispo by 8.
- …
> feat: Adjust how the starting disposition is affected by the sliders

- scripts/scr_controller_helpers/scr_controller_helpers.gml
The chapter management screen is empty after pressing the "chapter management" button.
Add a `scr_management(1)` call that was removed in https://github.com/Adeptus-Dominus/ChapterMaster/pull/617 .
None
Launched the game and the management screen works again.
https://discord.com/channels/714022226810372107/1121959429546455050/1353048934733451457
Exclude
> fix: Management view not showing up

- objects/obj_controller/Step_0.gml
- scripts/exp_and_exp_growth/exp_and_exp_growth.gml
- scripts/scr_ComplexSet/scr_ComplexSet.gml
- scripts/scr_complex_colour_kit/scr_complex_colour_kit.gml
- scripts/scr_controller_helpers/scr_controller_helpers.gml
- scripts/scr_draw_management_unit/scr_draw_management_unit.gml
- scripts/scr_ui_manage/scr_ui_manage.gml
- scripts/scr_unit_quick_find_pane/scr_unit_quick_find_pane.gml
- Fix a bug that was causing the management view to open with the chapter view on top.
- Reduce step time on the management screen.
- Move the scr_management call, so that "apparently" it's not called when not needed.
- Improve step performance by precalculating most of the performance intensive unit view stats once, instead of every step.
- Kill some show_debug stuff, because it was flooding the output.
Kill the `max_health` calls on the management view, as it eats 3ms by just existing for 33 units on the screen every step.
Both fleet and system unit management now opens properly.
Step time on the management screen is improved by ~3-4 ms.
https://discord.com/channels/714022226810372107/1353143470923059290
> fix: Unit management view breaking and win some step time

- objects/obj_en_fleet/Alarm_1.gml
- objects/obj_p_fleet/Alarm_1.gml
- scripts/scr_crusade/scr_crusade.gml
- scripts/scr_enemy_ai_d/scr_enemy_ai_d.gml
- scripts/scr_fleet_functions/scr_fleet_functions.gml
- scripts/scr_player_fleet_functions/scr_player_fleet_functions.gml
- scripts/scr_random_event/scr_random_event.gml
- scripts/scr_star_travel_algorithm/scr_star_travel_algorithm.gml
- scripts/scr_unit_quick_find_pane/scr_unit_quick_find_pane.gml
make the crusading event naturally spawn in game again
also make some improvements to code base
ensure crusades are always reachable by player by creating get_viable_travel_time function which uses the fastest route algorithm to ensure a location can always be reached by at least 1 fleet with a margin of 10 turns (reachable margin can be augmented as required)
- allow the crusade1 2 and 3 actions to be sent into the set fleet movement function
use "event crusade" cheat to spawn crusade and send player fleet on crusade
None
> fix: Crusade event spawns again

- datafiles/main/chapters/32.JSON
- Fix obsolete advantage name.
- Fix 0 starting disposition with all factions (why do you have to do it manually???).
- Proper advantage name.
- Copy disposition values from a custom chapter with the same stats.
None
- New game as Tome Keepers.
https://discord.com/channels/714022226810372107/1121959429546455050/1354871109668966472
> fix: Tome Keepers psyker advantage and starting disposition

- objects/obj_enunit/Alarm_0.gml
- objects/obj_enunit/Create_0.gml
- objects/obj_pnunit/Create_0.gml
- scripts/scr_en_weapon/scr_en_weapon.gml
- Fix bugs.
- Make the code more readable and simple.
- Account for the most of edge cases.
- The code is refactored to be more readable.
- The new engaged check is taken from the combat overhaul branch.
- Most of the target selection edge cases are accounted for, with retargeting, stopping to look for vehicles or attacking vehicles instead.
- A couple of log error added, to keep track if some stuff breaks.
None
- A lot. Like, a lot, a lot, to fix this shit. I can only hope that I wasn't lucky to miss some apparent shit.
https://discord.com/channels/714022226810372107/714023282780799028/1355327467686068314
https://discord.com/channels/714022226810372107/1121959429546455050/1355359142205853858
#579 
> refactor: And fix enemy ranged targeting

- scripts/scr_ComplexSet/scr_ComplexSet.gml
stop ill fitting cloaks on dreads and scouts
add check for the correct body_type to add base cloak
test game compile and check no scouts spawning with ill fitting cloaks
https://discord.com/channels/714022226810372107/1354643086860619908
> fix: Stop cloaks being drawn on scouts

- objects/obj_ncombat/Alarm_5.gml
- scripts/scr_after_combat/scr_after_combat.gml
- sprites/spr_left_pauldron_fur_hanging/spr_left_pauldron_fur_hanging.yy
- sprites/spr_right_pauldron_fur_hanging/spr_right_pauldron_fur_hanging.yy
- sprites/spr_scout_colors/spr_scout_colors.yy
- sprites/spr_scout_complex/spr_scout_complex.yy
- sprites/spr_scout_heads/spr_scout_heads.yy
- sprites/spr_scout_new/spr_scout_new.yy
- sprites/spr_term_left_fur_hanging/spr_term_left_fur_hanging.yy
- sprites/spr_term_right_fur_hanging/spr_term_right_fur_hanging.yy
Slime now does not destroy armours it just adds a forge point hit for that turn using the existing infrastructure for adding maintenance points for de-equipped armour. 
Essentially doubles the maintenance of the armour for that turn. So the slime barekly effects mk7 armour but for a mk3 adds a chunk of forge point hit
potential fix tot nuking it
plenty of alternatives this is just one quick option
very little but if thjis route is alright or can be made to work thenm i'll do more
None
> feat: Slime increases armor maintenance, without destruction

- objects/obj_ncombat/Alarm_5.gml
- objects/obj_ncombat/KeyPress_13.gml
- To make the reward table a bit more predictable and simple.
- Exp and Req reward formulas are now `_quad_factor * sqr(threat);`. Exp has the factor of 10, and Req of 6.
- In practice, this means that the rewards are a bit smaller at lower levels, but higher at high levels.
None
None
None
> feat: Adjust after battle EXP and Req rewards

- objects/obj_popup/Draw_0.gml
- scripts/exp_and_exp_growth/exp_and_exp_growth.gml
- scripts/is_specialist/is_specialist.gml
- scripts/scr_company_struct/scr_company_struct.gml
- scripts/scr_complex_colour_kit/scr_complex_colour_kit.gml
- scripts/scr_culture_visuals/scr_culture_visuals.gml
- scripts/scr_draw_unit_image/scr_draw_unit_image.gml
- scripts/scr_drop_fiddle/scr_drop_fiddle.gml
- scripts/scr_manage_task_selector/scr_manage_task_selector.gml
- scripts/scr_marine_struct/scr_marine_struct.gml
- scripts/scr_player_combat_weapon_stacks/scr_player_combat_weapon_stacks.gml
- scripts/scr_random_marine/scr_random_marine.gml
- scripts/scr_roster/scr_roster.gml
- scripts/scr_special_view/scr_special_view.gml
- scripts/scr_ui_manage/scr_ui_manage.gml
- Removes the need to use transfer to assign support command.
- Specialists can now be selected with the same buttons as captains and other command squad marines.
- `special_role_slot_open` function.
- Refactor `role_groups` and `is_specialist` functions.
None
Loading executing marines then reassigning the roles.
Assigning on empty companies.
Reading on attack and raid tooltip/
None
> feat: Specialist assignment buttons for companies and a refactor

- .github/workflows/gamemaker_build.yml
- Not have to edit the runtime ver every time we update.
- Remove the related line from the workflow.
- It should automatically parse it from the yyp file. Before it didn't work, because of the old yyp format, now it should.
None
None
None
> ci: Remove the specific runtime ver, it should parse it by itself now

- objects/obj_enunit/Create_0.gml
- objects/obj_enunit/Draw_0.gml
- Fix a crash.
- Move the color selection to create event.
- Keep the column color within the planet colors array size, and set it to gray if it goes beyond.
- Not sure if anything should be done about having single enemies as `enemy=30`.
- The bug: https://discord.com/channels/714022226810372107/1356776712410763584
> fix: Single enemy fight crash, due to column colour

- objects/obj_tooltip/Draw_75.gml
- scripts/scr_hit/scr_hit.gml
- The tooltip offset was not working as intended.
- Flip logic was also a bit broken.
- The tooltip was often covering text/buttons you're hovering over.
- Screen padding var no longer affects the offset when flipping.
- The offset from the cursor is 20 pixels, getting properly mirrored when the tooltip is flipped.
- The offset and screen edge padding don't take scale and offset (if not in the UI layer) from `scr_tooltip_draw` into account.
- Checked that tooltips properly work in the shop and unit view.
- None.
> fix: Proper tooltip offset from the cursor and flipping

- scripts/scr_company_view/scr_company_view.gml
- scripts/scr_ui_manage/scr_ui_manage.gml
- Fix a bug where Champion and Ancient company assignment screens displayed no or wrong units.
- Flip `opposite: false` to `true` for champions and ancients.
- Refactor some code, while I'm here. The proper refactor will come in the next PR.
- Also added a `company > -1` check into `other_manage_data()`, as I saw a crash related to it.
- This whole code chunk is not good.
- Confirmed that role assignments work correctly.
- Bug report: https://discord.com/channels/714022226810372107/1356998884127277156
> fix: Champion and Ancient broken company assignments

- objects/obj_controller/Create_0.gml
- objects/obj_controller/Mouse_61.gml
- scripts/is_specialist/is_specialist.gml
- scripts/macros/macros.gml
- scripts/scr_company_view/scr_company_view.gml
- scripts/scr_manage_task_selector/scr_manage_task_selector.gml
- scripts/scr_roman_numerals/scr_roman_numerals.gml
- scripts/scr_scrollbar/scr_scrollbar.gml
- scripts/scr_special_view/scr_special_view.gml
- scripts/scr_ui_manage/scr_ui_manage.gml
- Stop the code from being so funny.
- Fix company screen not displaying all units when more than 2 specialist buttons exist.
- Fix managing screen closing after pressing exit on the command squad assignment.
- Refactored stuff into a single data structure with a loop.
- For the second fix I just replaced the old hardcoded `+2` to max unit count, for array length of all possible specialist buttons.
- For the last fix, I replaced `managing = unit.company` for `managing = selection_data.system`.
- Something got broken, and the game crashes when opening any specialist branch (not related to buttons or anything).
- The error is absolutely weird. It just says that the `scr_ui_manage` script crashed on the first most line, and yes, even if I move the function on the first line, it crashes on a …
> refactor: And fix command squad assigments code

- scripts/scr_log/scr_log.gml
- The try and report loop error is supposed to show the dev_marker var but "(0)" is always shown instead, this is fixed here
> fix: try_and_report_loop arg passing

- scripts/scr_random_marine/scr_random_marine.gml
- scripts/scr_specialist_training/scr_specialist_training.gml
- Hopefully, fix an error.
- Add a new possible random_marine requirement - job.
- Set the job requirement to "none" on all specialist training.
- Nothing?
- Bug report: https://discord.com/channels/714022226810372107/1356913362616844349
> fix: Ensure that specialist training only takes unemployed marines

- objects/obj_mass_equip/Draw_0.gml
- Fix a crash when trying to mass equip the dreadnought role.
- Add the dreadnought to the infantry list, for the purposes of equipment gathering.
- Nothing.
- Successfully changed dreadnought equipment on the mass equip screen.
- None.
> fix: Dreadnought mass equip crash

- scripts/scr_initialize_custom/scr_initialize_custom.gml
Allow squads widely variable loadouts to be put in different formations. 
- Possibly making formation options a general location vs role specific eg (Row 1, 2, 3, & 4) vs (Assault, Tactical, Devastators, Scouts)
- None and I understand the risks. This is a very minor change that wont break anything
- None.
> feat: Allow more column options for battleline squads

- scripts/scr_arti_descr/scr_arti_descr.gml
- scripts/scr_ship_battle/scr_ship_battle.gml
- Fix a crash happening at ship battle initialization, following the daemonic artifact destruction.
- Role check fix.
- Add a tip into the daemonic artifact description, about what can happen.
- The following battle is funny. I think there is only one greater daemon that gets EXPLODED in 1 turn.
- Spawned daemonic artifacts and forced the battle - no crash, but the battle is weird, almost broken.
- None.
> fix: Daemon artifact ship battle crash and a tip about destroying

- objects/obj_mass_equip/Step_0.gml
- Fix a weird `Unable to find any instance for object index '0' name 'obj_al_capital'` crash, that I assume is caused by armor not being a struct, but a ship instead? No idea.
- Some failsafes to ensure that armor is properly assigned before trying to use methods.
- Perhaps having an early return, if it still remains not a struct, may be good, but I rather it fail and shot that something went very wrong.
- Mass equipped devastator slots a couple of times.
- Bug report: https://discord.com/channels/714022226810372107/1358478404734681259
> fix: Mass equip invalid armor failsafe

- scripts/scr_draw_management_unit/scr_draw_management_unit.gml
- Stop squad colors from repeating, at least a bit.
- Squad colors array is now made of 27 colors, vs 10.
- First 9 colors are hue shifts, with some colors removed, due to very close similarity. Next 9 have the same hue, but lightness value reduced by half. Next 9 have their saturation reduced by half instead.
- More **distinct** colors.
- Checked how the squads look - it's okay, but can be better.
- None.
> feat: More squad marker colors

- objects/obj_popup/Mouse_50.gml
- scripts/scr_company_order/scr_company_order.gml
- scripts/scr_initialize_custom/scr_initialize_custom.gml
- scripts/scr_squads/scr_squads.gml
- The idea behind Sternguard and Vanguard is cool and lore friendly, but in my opinion just doesn't work properly atm. 
- What you get, are weird, self assigning units, with no logic behind the assignment.
- I don't think that having them right now, in their current state, outweighs their clunkiness, and I can't bother with properly solving that, as I personally don't need it that much.
- I do think that having them merged, **for now**, is better than maintaining the status quo, and hoping that one day someone will repair them.
- The removal/addition is a couple lines of code, so nothing is really lost.
- Vanguard and Sternguard squads are converted into normal Veteran squads.
- The loadout of these new squads is very similar to Sternguard loadout, consider these to be "Tacticals+".
- If …
> feat: Sternguard and Vanguard > Veteran; Loadout adjustments

- scripts/scr_ui_manage/scr_ui_manage.gml
- Nothing.
- tested with black templars
- None.
> fix: Remove "Librarian Required" button when Psyker Intolerant

- objects/obj_main_menu/Create_0.gml
- scripts/__init_global/__init_global.gml
- scripts/scr_log/scr_log.gml
- Improve error logging and provide more info to solve bugs.
- Declare a couple of globals through pragma, to ensure that they are always defined.
- Create a copy of "last_messages" on every error popup.
- State the current turn, chapter name and game seed in the error log.
- Include only the error details into the `show_debug_message` call.
- Add support for adding OS into the error log, when it will be needed.
- Probably more info can be added. I just did some basic guess work.
- I didn't make it so that saves, error logs, and message logs get packed into an archive, because I see no reason. 
- Packing all saves will eat a lot of space, and I can't take just the latest.
- If people can't open the folder to upload 2 files to discord, they are not going to do it with just 1 either. It's …
> chore: Error logging improvments

- scripts/scr_ComplexSet/scr_ComplexSet.gml
- scripts/scr_complex_colour_kit/scr_complex_colour_kit.gml
- scripts/scr_culture_visuals/scr_culture_visuals.gml
- scripts/scr_draw_unit_image/scr_draw_unit_image.gml
- Revert the PR that is loop softlocking the game with errors on the unit view, when it's compiled with YYC.
- Revert the PR and also comment out some debug lines.
- Nothing.
- Compiled with YYC - the error is no more.
```
ERROR in action number 1
of  Step Event0 for object obj_controller:
Unbalanced surface stack. you are trying to pop a surface that has not been set.
gml_Script_draw@anon@23022@ComplexSet@scr_ComplexSet (line 490)
gml_Script_scr_draw_unit_image (line 686)
gml_Object_obj_controller_Step_0 (line 689)
ERROR in action number 1
of  Step Event0 for object obj_controller:
Trying to set a surface target that does not exist.
gml_Script_scr_draw_unit_image (line 860)
gml_Object_obj_controller_Step_0 (line 689)
```
> revert: "fix: Safety tweaks to unit draw surfaces (#715)"

- objects/obj_en_fleet/Alarm_1.gml
- objects/obj_p_fleet/Alarm_1.gml
- objects/obj_star/Alarm_1.gml
- scripts/scr_PlanetData/scr_PlanetData.gml
- scripts/scr_imperial_navy_functions/scr_imperial_navy_functions.gml
- scripts/scr_mission_functions/scr_mission_functions.gml
- scripts/scr_recruit_data/scr_recruit_data.gml
- scripts/scr_system_search_helpers/scr_system_search_helpers.gml
- Creates static methods within PlanetData to alter planet disposition this has two advantages
- removes the need to use the clunky system.dispo[planet] syntax
- remove teh need to constatly define clamp(val, 0, 100)
- ensure that planet disposition is set whenever a player fleet is present ata planet removing the ```???``` disposition error that sometimes occurs
- Nothing.
- Loaded game and played a few turns
- None.
> fix: Rework planet dispo to work with PlanetData

- scripts/scr_unit_size/scr_unit_size.gml
- Fix a typo? Bug? Mistake?
- Destroy the ds_map when it's no longer needed, as it was created on **every** `scr_unit_size` function call and never destroyed, possibly leading to insane memory leaks.
- Nothing.
- https://discord.com/channels/714022226810372107/1121959429546455050/1363869559009837157
> fix: Destroy a runaway unit_size ds_map

- objects/obj_star/Draw_0.gml
- scripts/scr_ComplexSet/scr_ComplexSet.gml
- scripts/scr_culture_visuals/scr_culture_visuals.gml
- scripts/scr_draw_unit_image/scr_draw_unit_image.gml
- Fix sprite creation memory leaks.
- Remove empty leftover surfaces stuck in the memory when not needed anymore.
- Rename `clear_and_free_surface` into `surface_clear_and_free`, to be a bit more standardized.
- Replace the remaining `surface_free` calls with `surface_clear_and_free`.
- Free one of the surfaces that was stuck in the memory.
- Only create a helm sprite if one doesn't exist.
- Nothing.
- Launched the game a lot of times to test each change.
- None.
> fix: Helm sprite memory leak; Surface freeing and clearing

- objects/obj_ncombat/Alarm_3.gml
- objects/obj_ncombat/Alarm_5.gml
- scripts/scr_flavor2/scr_flavor2.gml
- Reduce the amount of unneed red in the battlelog, when units are injured and not yet lost.
- Change coloring of some lines and some text.
- Now, only when units are actually lost, the line will be colored red.
- Nothing.
- None.
> feat: Less red in the battlelog

- objects/obj_garbage_collector/Step_0.gml
- scripts/scr_ComplexSet/scr_ComplexSet.gml
- scripts/scr_buttons/scr_buttons.gml
- scripts/scr_complex_colour_kit/scr_complex_colour_kit.gml
- scripts/scr_culture_visuals/scr_culture_visuals.gml
- scripts/scr_livery_setup/scr_livery_setup.gml
- remove right hand side sprite in selector it is now redundant
- add some tooltips to try explain whats going on
- fix a bundle of broken weapon sprites
- Nothing.
- None.
> fix: Remaining sprite weapon issues and streamline customiser

- objects/obj_creation/Create_0.gml
- scripts/NameGenerator/NameGenerator.gml
- Fix NameGenerator throwing an error and generating generic names after x amount of new games.
- All static vars are now instance vars. I see no reason to have them as static. They shouldn't be static and should reset each instance creation.
- Recreate the NameGenerator on obj_creation create event, to ensure that instance vars are nulled if the player goes back and forth.
- Don't create NameGenerator in the script file. Creation object should be enough.
- Nothing.
- 6 new games back to back - no generic names observed and no errors.
- Bug report: https://discord.com/channels/714022226810372107/1366704470091894844
- Bug report 2: https://discord.com/channels/714022226810372107/1365501015628972152
> fix: NameGenerator breakage

- objects/obj_creation/CleanUp_0.gml
- objects/obj_creation/Create_0.gml
- scripts/__init_global/__init_global.gml
- Fix a bug I introduced.
- Create NameGenerator through pragma.
- Recreate it in the cleanup of creation, as opposed to entering (no reason as to why, really, just because controller also does the same).
- I'm not sure if it's easier to just do this in the main menu create, but I feel really weird putting anything like this into the main menu obj.
- New game, save, load, exit the game, load.
- Bug report: https://discord.com/channels/714022226810372107/1368062589711421471
> fix: NameGenerator not initialized when loading

- scripts/scr_ui_formation_bars/scr_ui_formation_bars.gml
- scripts/scr_ui_settings/scr_ui_settings.gml
- Fix custom formations having unchangeable type (raid/attack).
- Refactor some related code.
- Fix the main issue.
- Return formation type tooltips.
- Edit the tooltip text a bit.
- Nothing.
- Checked how everything works in the game.
- Bug report: https://discord.com/channels/714022226810372107/1367669786288586795
> fix: Type change for custom formations and tooltips

- objects/obj_crusade/Mouse_50.gml
- objects/obj_turn_end/Create_0.gml
- Fix a crash.
- Initialize the `audience` variable in the create event of `obj_turn_end`. Hopefully should prevent the crash.
- Nothing.
- Bug report: https://discord.com/channels/714022226810372107/1377098248195670056
```
Error Details:
ERROR in action number 1
of Mouse Event for Glob Left Button for object obj_crusade:
Variable Get 91 (102053, -2147483648)
Stacktrace:
gml_Object_obj_crusade_Mouse_50 (line 13)
```
> fix: Crusade crash (audience variable init)

- scripts/scr_initialize_custom/scr_initialize_custom.gml
Similarly to the #884 , the 4 servo arms, needed for techmarine duties, when `sieged` disadvantage is selected, are missing.
This pull request adds them.
- No testing was performed for such a simple fix.
https://discord.com/channels/714022226810372107/1386621454682165349
> fix: Add stockpiled Servo-arms for Sieged chapters

- scripts/scr_flavor2/scr_flavor2.gml
Fixes misleading statements about no damage - damage is dealt, and marine/hireling/vehicle(?) will lose hit points. It now should state if marine/hireling/vehicle(?) is downed (no longer an active combatant) or not.
- None, as it is a small and contained flavor text tweak.
https://discord.com/channels/714022226810372107/1398987282463068270 - bug report.
> fix: Combat Log
