Adeptus-Dominus/ChapterMaster

objects/obj_controller/Mouse_50.gml
objects/obj_popup/Mouse_50.gml
objects/obj_shop/Create_0.gml
scripts/scr_company_view/scr_company_view.gml
scripts/scr_dialogue/scr_dialogue.gml
scripts/scr_planetary_feature/scr_planetary_feature.gml
scripts/scr_ruins_reward/scr_ruins_reward.gml
scripts/scr_weapon/scr_weapon.gml

Updated the Mk 8 for more armor 
Reworked the ruins rewards so that you can find more type of Wargear. I also changed some of the text to be more loreful
Added the ruins on Feudal worlds
Balanced the prices(made some things more expensive and some cheaper in contrast to their damage/bonuses) and fixed some weapons that were duplicate in the code
More balancing done to weapons since I've made things too op last time
Made it so that you can now trade with the Mechanicus for skitarri(idk how to make it so that you could move them from HQ), Made the skitarii armor have some armor(it was 0 before, now is 5 which weaker than scout)
Added some text for the missing dialogues
Fixed a bug that prevent space marines from being transferred
Made the vehicles unable to be transferred to the HQ, thus …

Ruins Rewards reworked (plus more balances)

---

objects/obj_controller/Create_0.gml
objects/obj_controller/Mouse_50.gml
scripts/macros/macros.gml
scripts/scr_dialogue/scr_dialogue.gml
scripts/scr_load/scr_load.gml
scripts/scr_random_event/scr_random_event.gml
scripts/scr_save/scr_save.gml
scripts/scr_trade_add/scr_trade_add.gml

This will make the var for the next event an enum, now the event script can properly set it and eldar can tell you what the next event will be
This fixes this issue #6

Fix event eldar diplo

---

scripts/scr_weapon/scr_weapon.gml

Fixes issue with swapped weapon descriptions

Fixed swapped weapon description issue

---

scripts/scr_star_name/scr_star_name.gml

Fixed issue with missing planet names during map generation

---

ChapterMaster.yyp
objects/obj_drop_select/Draw_0.gml

Fix for the duplicated marine when on battle bug

Duplicated marines fix

---

ChapterMaster.yyp
scripts/scr_load/scr_load.gml
scripts/scr_planetary_feature/scr_planetary_feature.gml
scripts/scr_save/scr_save.gml

-fixed error with planet features saving
-made planet feature functions static

planet feature saving fixed

---

scripts/scr_battle_roster/scr_battle_roster.gml

The fix is marked with a comment. All other changes are whitespace changes using https://beautifier.io/ + some tiny code improvements (e.g. a = a + 1 => a++)

fixed CTD at battle start + beautified scr_battle_roster for readiblity

---

ChapterMaster.yyp
scripts/scr_load/scr_load.gml
scripts/scr_save/scr_save.gml
scripts/scr_ui_display_weapons/scr_ui_display_weapons.gml

Temporarily disabled save game file encryption, as a step towards implementing ironman and autosaves.
This will break old saved games.

Disable save file encryption

---

ChapterMaster.yyp
scripts/scr_vehicle_order/scr_vehicle_order.gml

fixed CTD in Armamentarium and at battle end

---

scripts/scr_ui_formation_bars/scr_ui_formation_bars.gml

and formation related CTDs
ready for CR and merge

fixed CTD after exiting Chaos Emmissary view

---

objects/obj_main_menu/Step_0.gml

removed random voiceover in main menu

---

ChapterMaster.yyp
scripts/scr_start_load/scr_start_load.gml

fixed the escort load option on chapter generation

fixed escort load  (bug)

---

objects/obj_turn_end/Alarm_0.gml
objects/obj_turn_end/Alarm_4.gml

ready for review and merge.
should fix long battles CTD issue:

fixed typos in obj_turn_end alarms

---

scripts/scr_ui_advisors/scr_ui_advisors.gml

ready for review and merge
ss:

test slave batches now display again

---

scripts/scr_initialize_custom/scr_initialize_custom.gml

- Fixed extra ; after else and if statements (caused errors)

Hotfix: fixed red errors on the feather message screen in GM2

---

objects/obj_creation/Create_0.gml
scripts/scr_chapter_new/scr_chapter_new.gml
scripts/scr_initialize_custom/scr_initialize_custom.gml

Added the Crimson Fists chapter

The Fists 3 RED

---

scripts/scr_ui_display_weapons/scr_ui_display_weapons.gml

- Fixed double arms for tartaros and termies
- Minor == update to code
-

fix: double arms on tartaros and termies

---

scripts/scr_load/scr_load.gml
scripts/scr_save/scr_save.gml

fixes bug with saving after #94 merge

save load options bug

---

objects/obj_creation/Create_0.gml
scripts/scr_chapter_new/scr_chapter_new.gml
scripts/scr_initialize_custom/scr_initialize_custom.gml

Red Lightning

---

scripts/scr_cheatcode/scr_cheatcode.gml

fixed recruit cheat causing CTD + beautified scr_cheatcode

---

objects/obj_controller/Alarm_5.gml

fixed ctd on 2nd turn after recent refactor

---

scripts/scr_ui_popup/scr_ui_popup.gml

- adds a tool tip over the year in the main start map so player can see turn counter, as per dev meeting
- light refactor or scr_ui_popup

turn marker tool tip

---

objects/obj_controller/Step_0.gml
objects/obj_star/Alarm_4.gml

- fixes two minor crashes coming from one syntax error from missing brackets and one missing variable assignment

post merge tweaks

---

objects/obj_controller/Alarm_1.gml

- Deleted a coment which was causing slow downs on system generation

Hotfix: deleted logs which caused slow downs

---

scripts/scr_special_view/scr_special_view.gml

- Add missing semi colomn causing crash

Hot-fix: missing semi colomn crash

---

objects/obj_bomb_select/Mouse_56.gml

as in title refactor error caused crash with bombard

refactor niggle with bombard

---

ChapterMaster.yyp

All looks fine, no issues or errors
Here's the release notes: https://gms.yoyogames.com/ReleaseNotes.html (haven't noticed anything really useful for us, just some bugfixes here and there)
Ready for review and merge

Upgraded GM to 2023.8.2.106

---

code_guidance.md

new pull seems to solve problem

add code guidance

---

scripts/scr_enemy_ai_a/scr_enemy_ai_a.gml
scripts/scr_enemy_ai_b/scr_enemy_ai_b.gml

tweaked the numbers down a little bit as per dev discussions otherwise a straight copy of #52

[made by Frost] disposition system changes with tweaks

---

objects/obj_popup/Mouse_50.gml
scripts/scr_company_view/scr_company_view.gml
scripts/scr_initialize_custom/scr_initialize_custom.gml
scripts/scr_marine_struct/scr_marine_struct.gml
scripts/scr_save/scr_save.gml
scripts/scr_ui_manage/scr_ui_manage.gml

- fixes crash when promoting marines
- fixes marine disappearance when promoting marines
- fixes ui bug where more slots are created than there are units in the company
- fixes promoting bug where unit role does not change
- also contains duplicating vehicle fix
is branch of #176 and will need to be reviewed and merged after it but made separate pr to make prs more concise

Wiped out company restock

---

scripts/scr_move_unit_info/scr_move_unit_info.gml

should solve final boarder bug I hope

bug wrong company and unit set in unit struct

---

objects/obj_star_select/Mouse_50.gml
objects/obj_star_select/Step_0.gml
scripts/scr_move_unit_info/scr_move_unit_info.gml
scripts/scr_ui_popup/scr_ui_popup.gml

fixes a ui error where the build button always displays build instead of the structure that's been built

build button text fix (bug) 8.2.1

---

objects/obj_controller/Step_0.gml
scripts/scr_initialize_custom/scr_initialize_custom.gml
scripts/scr_ui_manage/scr_ui_manage.gml

- fixes issue #180 and associated issues

crash on first view to company screen (bug)

---

scripts/scr_save/scr_save.gml

-speeds saving up string was accidentally reverted during refactor of save

wrong string bogging saving

---

objects/obj_star_select/Step_0.gml

should solve all further planet button issues

mystery build button

---

objects/obj_controller/Step_0.gml
objects/obj_popup/Mouse_50.gml
scripts/scr_add_item/scr_add_item.gml
scripts/scr_item_count/scr_item_count.gml

solves the title bugs from the bug reports

56 item limit and disappearing specialist heads bug fixes

---

objects/obj_popup/Mouse_50.gml
scripts/scr_item_count/scr_item_count.gml
scripts/scr_marine_struct/scr_marine_struct.gml
scripts/scr_move_unit_info/scr_move_unit_info.gml
scripts/scr_squads/scr_squads.gml

- should fix the final equipment crash errors

Fix final equipment crashes

---

objects/obj_popup/Mouse_50.gml

minor bug where right item would display as left item directly after re-equip for 8.2.1

left right swap bug

---

objects/obj_creation/Draw_0.gml
objects/obj_creation_popup/Draw_0.gml
scripts/scr_load/scr_load.gml
scripts/scr_save/scr_save.gml
scripts/scr_ui_manage/scr_ui_manage.gml

- fixes loading of planet upgrade
- provides some belt and braces to hopefully solve the one recorded 8.2.1 crash (obj_ini.wid error)

solve loading upgrades

---

scripts/scr_load_all/scr_load_all.gml
scripts/scr_marine_struct/scr_marine_struct.gml
scripts/scr_move_unit_info/scr_move_unit_info.gml
scripts/scr_ui_manage/scr_ui_manage.gml

does what it says on the packet stops you being able to select planet side vehicles and offload them causing negative ship capacity values. also a minor unit size mismatch error cleared up.
changed a variable being set wrong which can cause an obscure CTD.
fixes roman numeral issue

unit sizes and select_All fault

---

scripts/scr_apothecary_ground/scr_apothecary_ground.gml
scripts/scr_item_count/scr_item_count.gml
scripts/scr_planetary_feature/scr_planetary_feature.gml

fixes the ancient starship and updates it to use new mechanics (e.g techmarine technology stats for repair)

fixes slaughter song

---

objects/obj_controller/Mouse_50.gml
scripts/is_specialist/is_specialist.gml
scripts/scr_company_view/scr_company_view.gml
scripts/scr_special_view/scr_special_view.gml
scripts/scr_ui_manage/scr_ui_manage.gml

- creates specialised methods for searching for different role sets (e.g pykers or tech based roles) rather than hardcoding if statements.
- improves existing is_specialist method
- for 8.3.0

specialist search refactor

---

scripts/scr_bomb_world/scr_bomb_world.gml
sprites/spr_gear_apoth/spr_gear_apoth.yy
sprites/spr_terminator2_colors/spr_terminator2_colors.yy
sprites/spr_weapon_assca/spr_weapon_assca.yy
sprites/spr_weapon_blank/spr_weapon_blank.yy
sprites/spr_weapon_colors/spr_weapon_colors.yy

- fixes bug where scr_bomb_worldwould crash due to unset variables
- did some refactor work while i was there

scr_bomb_world bug fix and refactor

---

scripts/scr_battle_roster/scr_battle_roster.gml

-  fixes a crash where in scr_battle_roster where the game would crash on trying to access veh_ranged because it dosn't exist anywhere in the game

veh_ranged doesn't exist bug

---

scripts/scr_enemy_ai_e/scr_enemy_ai_e.gml
scripts/scr_ui_advisors/scr_ui_advisors.gml

Blood Trial will no longer waste gene-seed if recruitment is halted

---

scripts/scr_crusade/scr_crusade.gml
scripts/scr_enemy_ai_a/scr_enemy_ai_a.gml
scripts/scr_enemy_ai_b/scr_enemy_ai_b.gml
scripts/scr_load_all/scr_load_all.gml

- loop with a misspelled variable was locking up the game on turn end

infinite loop bug (locks up game on turn end)

---

objects/obj_controller/Mouse_50.gml

- bug where all marines would be loaded instead of just the selected marines accident from refactor of loading marines to a struct method

load all bug

---

scripts/scr_enemy_ai_c/scr_enemy_ai_c.gml

- p_feature accidentally written as feature causing crash

bug fix misnamed reference

---

ChapterMaster.resource_order
ChapterMaster.yyp
objects/obj_controller/Create_0.gml
objects/obj_controller/Mouse_50.gml
objects/obj_star_select/Step_0.gml
scripts/scr_company_struct/scr_company_struct.gml
scripts/scr_company_struct/scr_company_struct.yy
scripts/scr_squads/scr_squads.gml
scripts/scr_ui_manage/scr_ui_manage.gml

start organising companies into temporary structs to reduce processing

Company struct

---

objects/obj_controller/Create_0.gml
objects/obj_creation/Create_0.gml
objects/obj_shop/Create_0.gml
objects/obj_shop/Draw_0.gml
scripts/scr_draw_unit_image/scr_draw_unit_image.gml
scripts/scr_initialize_custom/scr_initialize_custom.gml
scripts/scr_marine_struct/scr_marine_struct.gml
scripts/scr_weapon/scr_weapon.gml

Creates the requested heavy weapons pack for devestator.

heavy pack

---

objects/obj_controller/Alarm_5.gml
objects/obj_pnunit/Alarm_3.gml
scripts/scr_civil_roster/scr_civil_roster.gml
scripts/scr_marine_struct/scr_marine_struct.gml
scripts/scr_ship_battle/scr_ship_battle.gml

- fixes bug with death company and an inability to equip dreadnought armour

Refactor weapons bug fixes

---

scripts/scr_company_struct/scr_company_struct.gml

bug where canceling a squad mission would CTD

cancel assignment bug

---

scripts/scr_marine_struct/scr_marine_struct.gml

fixes a CTD when adding bionics

bionics fix

---

scripts/scr_weapon/scr_weapon.gml

solves ui bug with correct gear not showing

gear not showing in ui equip area

---

objects/obj_popup/Mouse_50.gml
scripts/is_specialist/is_specialist.gml
scripts/scr_battle_roster/scr_battle_roster.gml
scripts/scr_chapter_new/scr_chapter_new.gml
scripts/scr_company_order/scr_company_order.gml
scripts/scr_initialize_custom/scr_initialize_custom.gml
scripts/scr_squads/scr_squads.gml

Adds 3 squads assault terminators, vanguard and sternguard vets. Rebalances existing squad weapon loadouts.

3 new squads and loadout balancing

---

objects/obj_drop_select/Draw_0.gml

Small word choice change as requested by "Saltlord"

word changes

---

objects/obj_controller/Mouse_50.gml
objects/obj_p_assra/Alarm_0.gml
objects/obj_p_assra/Step_0.gml
objects/obj_p_ship/Alarm_0.gml
objects/obj_popup/Mouse_50.gml
scripts/scr_marine_struct/scr_marine_struct.gml
scripts/scr_ui_manage/scr_ui_manage.gml

- Brings borders weaponry inline with the new weapons profiles
- adds a dedicated marker called is_boarder in the unit struct rather than using decimals in the marines age to determine if the unit was a boarder which was just batshit

boarders overhaul

---

ChapterMaster.resource_order
ChapterMaster.yyp
objects/obj_controller/Create_0.gml
objects/obj_controller/Draw_0.gml
objects/obj_controller/Step_0.gml
objects/obj_p_assra/Step_0.gml
objects/obj_p_ship/Alarm_0.gml
objects/obj_p_ship/KeyPress_66.gml
objects/obj_p_ship/Step_0.gml
objects/obj_shop/Create_0.gml
objects/obj_shop/Draw_0.gml
objects/obj_shop/Step_0.gml
scripts/macros/macros.gml
scripts/scr_add_stc_fragment/scr_add_stc_fragment.gml
scripts/scr_boarding_actions/scr_boarding_actions.gml
scripts/scr_boarding_actions/scr_boarding_actions.yy
scripts/scr_company_struct/scr_company_struct.gml
scripts/scr_draw_unit_stat_data/scr_draw_unit_stat_data.gml
scripts/scr_librarium/scr_librarium.gml
scripts/scr_marine_struct/scr_marine_struct.gml
scripts/scr_perils_table/scr_perils_table.gml
scripts/scr_ui_manage/scr_ui_manage.gml
scripts/scr_ui_popup/scr_ui_popup.gml
scripts/scr_ui_settings/scr_ui_settings.gml
scripts/scr_weapon/scr_weapon.gml

- fixes too many stcs being added upon stc recovery
- fixes a previously thought solved crash with the perils of the warp table
- revamps all toooltips curtesy of ettykitty
- lid variable causing crash

First patches stc, perils crash and etty tooltips

---

scripts/scr_load/scr_load.gml

wrong typing on p_timer causing save errors

---

objects/obj_p_fleet/Step_0.gml
objects/obj_popup/Step_0.gml
scripts/scr_ork_fleet_functions/scr_ork_fleet_functions.gml

crash from incorrect name scope in the new ork fleet code

ork fleet scope error

---

.github/pull_request_template.md

ci: Update pull_request_template

---

.github/workflows/pr-title-checker.yml

- add `ready_for_review`, `synchronize` and `review_requested` triggers for the title checker, to hopefully stop it from freezing and not checking the title sometimes.

ci: Title checker updates

---

objects/obj_enunit/Alarm_1.gml
scripts/scr_en_weapon/scr_en_weapon.gml
scripts/scr_shoot/scr_shoot.gml
scripts/scr_weapon/scr_weapon.gml

- Assigns new HP, AC, and Damage resist values to enemy ground forces
- integrates enemy weapons into the new arp system
-Continuation of the larger #315 PR addressing enemy durability

feat: combat-overhaul part2

---

objects/obj_main_menu_buttons/Step_0.gml

- fixes misbehaving exit button causing weird behaviour
- ui bugfix
- https://discord.com/channels/714022226810372107/1335134498643247186

fix: Random exit from creation screen on click

---

objects/obj_popup_dialogue/Step_0.gml

- Hopefully it won't break (it'll).

feat: Add pasting support for cheats

---

scripts/scr_bomb_world/scr_bomb_world.gml

- Makes Bombard purging reduce corruption.
- Hopefully allows players to make a opening to do more effective purging tactics without killing the entire planet.

feat: Make Bombard purging reduce corruption

---

objects/obj_controller/Alarm_7.gml
objects/obj_controller/Create_0.gml
objects/obj_fleet/Create_0.gml
objects/obj_fleet/Step_0.gml
objects/obj_garbage_collector/Step_0.gml
objects/obj_ncombat/Alarm_7.gml
objects/obj_ncombat/Create_0.gml
scripts/JsonFileListLoader/JsonFileListLoader.gml
scripts/NameGenerator/NameGenerator.gml
scripts/debugl/debugl.gml
scripts/scr_array_functions/scr_array_functions.gml
scripts/scr_chapter_new/scr_chapter_new.gml
scripts/scr_company_view/scr_company_view.gml
scripts/scr_crusade/scr_crusade.gml
scripts/scr_event_dudes/scr_event_dudes.gml
scripts/scr_fleet_functions/scr_fleet_functions.gml
scripts/scr_hit/scr_hit.gml
scripts/scr_image/scr_image.gml
scripts/scr_initialize_custom/scr_initialize_custom.gml
scripts/scr_khornate_fleet_functions/scr_khornate_fleet_functions.gml
scripts/scr_load/scr_load.gml
scripts/scr_load_controller/scr_load_controller.gml
scripts/scr_necron_tombs/scr_necron_tombs.gml
scripts/scr_planetary_feature/scr_planetary_feature.gml
scripts/scr_random_event/scr_random_event.gml
scripts/scr_save/scr_save.gml
scripts/scr_save_controller/scr_save_controller.gml

- Overhauls the debug logging system by replacing the legacy 'debugl' calls with a new set of logging functions (log_message, log_error, log_warning) that provide more contextual information.
- Propagate these new logging calls throughout the codebase.
- Improve click error debugging.
- Change garbage collection debug message to log one time, instead of separate for each line. Should reduce ini manipulation overhead.

feat: Rework how debugl is used and works

---

scripts/scr_random_event/scr_random_event.gml

- Disables crusades, chaos invasion and never forgive events, also add comments.
- Broken or extremely unbalanced events.
- https://discord.com/channels/714022226810372107/714023282780799028/1339707335458816124

fix: Disable annoying events

---

.github/pull_request_template.md

Restructure the PR template, to hopefully make it more usable and intuitive.
- Remove checkboxes, as they were cluttering the PR view on the list page.
- Reorder sections, to follow the flow of thought better (I think?).
- Add "Alternatives considered" section, to provide more insight into the line of thinking of the contributor.
- Move tips under each section.
- Source of "inspiration": https://raw.githubusercontent.com/CleverRaven/Cataclysm-DDA/refs/heads/master/.github/pull_request_template.md

ci: Edits to the pull request template

---

scripts/scr_initialize_custom/scr_initialize_custom.gml

-Fixes bug causing chapters starting with obliterated and equal specialist distribution to have more troops than intended

fix: Equal specialist distr fix for obliterated

---

docs/README.md

Make the readme nicer, better structured and easier to read.
- Move most of the compiling stuff onto a separate wiki page.
- Add coderabbit badge.
- Add "Playing" section.
- Add wip "Contributing" section, together with a wip wiki page.
- Integrated links from their separate section into the first section.
Preview the file: https://github.com/Adeptus-Dominus/ChapterMaster/blob/docs/update-readme/docs/README.md

docs: Update README

---

.github/srvaroa_labeler.yml

- Better represent the size of the PR with labels.
- Add new size dependant labels and adjust the existing one.

ci: Better Pull Request size labels

---

.github/srvaroa_labeler.yml

ci: Proper Pull Request size labels

---

.github/pull_request_template.md

- Try to address the fact that most changes pass by undocumented to the players.
- Adds a section for "Player notes" to the PR template.
- Copy things written under the "Describe the solution", but they are most of the time technical and have a lot of things that players don't care about.
- https://discord.com/channels/714022226810372107/1121959429546455050/1343681825645662218

docs: Add "Player notes" section to the PR template

---

.github/size_labeler.yml

ci: Add "Warning!" size label

---

scripts/scr_log/scr_log.gml

chore: Stop my repo from appearing in error reports

---

scripts/scr_specialist_point_handler/scr_specialist_point_handler.gml

Make the forge respect company target.
Use `obj_controller.new_vehicles`.
Load game, build all vehicles.
https://discord.com/channels/714022226810372107/714023282780799028/1347359283515363359

fix: Forge respects target company

---

.github/workflows/stale_labeler.yml

I don't think it actually works, but what it does, is just updating all prs and bumping them to the top.
None
None
None
None
None

ci: Disable the stale labeler

---

datafiles/main/help.ini

Help people understand how marines grow, and try to make people understand how garrisoning works.
Simply adds some information to the help tab options.
Alternatives solutions would be to explain the garrisoning stuff under the squad menu, where it's more in the player's face when they're about to do it, so that they'll read that stuff. I don't know how often people really visit the help tab.
I made the changes, launched the game. And it works.
None
Added  more help information under the help tab to explain game mechanics

feat: More help information

---

ChapterMaster.yyp
datafiles/README.md

Have answers to some of the most often asked questions in one place.
Add a README.md file to the root of the game, with some questions and answers.
None.
None.
None.

docs: Readme file for the players

---

.github/pull_request_template.md

Usage of the smallest headers means that contributors cannot use any to separate their changes into blocks.
Player notes header name is a bit undescriptive.
Increase the header size of section by one.
Rename the player notes header into "Custom player notes entry" and set the default to "Use the PR title".
None
None
None
None

docs: Minor edits to the PR template

---

.github/workflows/gamemaker_build.yml

ci: Update the runtime version for the autobuild workflow

---

objects/obj_controller/Create_0.gml

Fix a bug.
Lower the requirement in compliance with the new system in the right place. Previously did that in the wrong place (scr_specialist_training.gml).
None
None
https://discord.com/channels/714022226810372107/1353142502882021446

fix: Librarian training requirement

---

datafiles/data/psychic_disciplines.json
datafiles/data/psychic_powers.json
objects/obj_controller/Step_0.gml

Fix a bug.
- Wrap the offending script into try-catch.
- Remove the non-existent power from the telekinesis discipline.
- Add a working replacement - "Assail", based on the power from the 7th ed.
None
Imperial Fist librarians no longer crash the game.
https://discord.com/channels/714022226810372107/1353344069455188079

fix: Telekenesis non-existent power crash

---

ChapterMaster.yyp

chore: The ghost file

---

objects/obj_controller/Step_0.gml
scripts/scr_clean/scr_clean.gml
scripts/scr_controller_helpers/scr_controller_helpers.gml
scripts/scr_draw_management_unit/scr_draw_management_unit.gml
scripts/scr_draw_unit_image/scr_draw_unit_image.gml
scripts/scr_drop_select_function/scr_drop_select_function.gml
scripts/scr_equipment_struct/scr_equipment_struct.gml
scripts/scr_marine_struct/scr_marine_struct.gml
scripts/scr_powers/scr_powers.gml
scripts/scr_shoot/scr_shoot.gml
scripts/scr_ui_manage/scr_ui_manage.gml

Make it beautiful.
- Pass the whole file through Gobo with max line width and 4 space indents.
- Then pass the entire file through a JS formatter, to make structs vertical again.
- Then manually fix all broken "$" string interpolations, as JS formatter likes to insert spaces before the symbol.
- No other changes made.
None
None
None

style: Format a bunch of scripts with Gobo and JS formatters

---

scripts/scr_equipment_struct/scr_equipment_struct.gml
scripts/scr_marine_struct/scr_marine_struct.gml

fix: A couple of things that the formatter broke

---

ChapterMaster.yyp
scripts/scr_ui_manage/scr_ui_manage.gml

undefined check causing crash
make more robust check set that resets last ship if the last ship is not in orbit
None
unload marines move fleet out of orbit and try reload marines
None

fix: Loading/Reloading marines onto ships, remove Undefined check

---

objects/obj_creation/Create_0.gml
scripts/scr_mission_functions/scr_mission_functions.gml

Restore init_garrison_mission to prevent crash when attempting to start garrison mission
find old copy of init_garrison_mission and add back in
None
None
None

fix: Restore init_garrison_mission to prevent crash

---

datafiles/data/psychic_powers.json
objects/obj_controller/Create_0.gml
objects/obj_controller/Step_0.gml
objects/obj_ncombat/KeyPress_13.gml
scripts/scr_load_controller/scr_load_controller.gml
scripts/scr_marine_struct/scr_marine_struct.gml
scripts/scr_perils_table/scr_perils_table.gml
scripts/scr_player_combat_weapon_stacks/scr_player_combat_weapon_stacks.gml
scripts/scr_powers/scr_powers.gml

- Repair max kills that were always unlimited, apparently.
- Bring more minor adjustments/improvements to the latest psy rework.
- Rename `max_kills` on powers to `additional_kills`, as that's 100% more descriptive.
- Change how `additional_kills` functions: 0 means no kills after the first one. -1 - unlimited kills. >1 - the specified amount of kills after the first one.
- Set all `additional_kills` to -1 on all non ap powers, and to 0 on all ap/anti-vehicle powers.
- Change `Crash` power to be a single target ap power.
- Remove the EXP requirement from librarians. They can continue their training as lexicanums, unlike other specialist types.
- Reduce another forgotten psy requirement for librarians (yes, there are 3 places, apparently).
- Adjust the psy tooltip a little.
- Powers limit …

feat: More psy adjustments

---

objects/obj_creation_popup/Draw_0.gml
objects/obj_enunit/Alarm_0.gml
objects/obj_fleet_select/Draw_0.gml
objects/obj_ncombat/Alarm_5.gml
objects/obj_ncombat/KeyPress_13.gml
objects/obj_pnunit/Alarm_3.gml
objects/obj_pnunit/Alarm_5.gml
objects/obj_popup/Step_0.gml
scripts/scr_complex_colour_kit/scr_complex_colour_kit.gml
scripts/scr_creation_home_planet_create/scr_creation_home_planet_create.gml
scripts/scr_librarium/scr_librarium.gml
scripts/scr_player_fleet_functions/scr_player_fleet_functions.gml
scripts/scr_player_ship_functions/scr_player_ship_functions.gml

Remove or comment out old or un-needed debug messages
check game compile

chore: Remove old debug messages

---

.github/pull_request_template.md

- Hopefully, improve the template even more.
- Remove/change things that were not used/underused.
- Make stuff more descriptive and intuitive (I hope).
None
None
None

ci: Yet another PR template edit

---

objects/obj_mass_equip/Step_0.gml

- Prevent critical crashing, hopefully.
- Make the code more readable.
- The whole step event is wrapped into try-catch.
- The entire file is formatted with gobo and then a JS formatter.
- The [bug](https://discord.com/channels/714022226810372107/1355658846122803351) that made me wrap this file into try-catch should be fixed.
- Force crash the mass equip screen. Seems to exit to chapter settings successfully.
- The bug: https://discord.com/channels/714022226810372107/1355658846122803351

chore: Try-catch mass_equip Step_0 and format

---

objects/obj_enunit/Draw_0.gml

- Fix a bug.
- Replaced `+=` with `=`.
- Fixed wrong variable name (wasn't reported, but I noticed it anyway).
- Nothing.
- Battle with orks. Checked that the composition is properly updated.
- Reported bug: https://discord.com/channels/714022226810372107/1356792241263349953

fix: Column composition_string not getting replaced

---

scripts/is_specialist/is_specialist.gml
scripts/scr_company_view/scr_company_view.gml

style: Format group_selection() and other_manage_data()

---

scripts/scr_enemy_ai_b/scr_enemy_ai_b.gml

- Fix a reported error.
- Add a `!= "none"` check.
- Nothing.
- Report: https://discord.com/channels/714022226810372107/1357153431751622680

fix: Error in enemy_ai_b

---

objects/obj_enunit/Alarm_1.gml
scripts/scr_en_weapon/scr_en_weapon.gml
scripts/scr_equipment_struct/scr_equipment_struct.gml
scripts/scr_marine_struct/scr_marine_struct.gml
scripts/scr_roster/scr_roster.gml
scripts/scr_shoot/scr_shoot.gml
scripts/scr_ui_manage/scr_ui_manage.gml
scripts/scr_weapon/scr_weapon.gml

Finish the CO project by bringing astartes durability down to similar levels of enemies
Adjustment of armor values and mods to make each MK distinct and indicitive of benefits and downsides
Removing damage reduction bonus from CON while increasing the hp bonus 
Adjust enemy Weapon damage values
Changing armor values
Compile, creation, combat X20
None

feat: combat overhaul part 3

---

scripts/scr_enemy_ai_b/scr_enemy_ai_b.gml

style: Format scr_enemy_ai_b

---

.github/workflows/release_dev.yml

- Fix an issue where the workflow fails if it's the first release on a new branch.
- Fix an issue where the changelog generation happens from the wrong tag, due to dev-old not existing when the generation happens.
- Everything. I really have no idea what I'm doing and just trying to make it work.
- None.

ci: Update release workflow

---

.github/labeler.yml
.github/pull_request_template.md
.github/release.yml
.github/srvaroa_labeler.yml
.github/stale_labeler.yml
.github/workflows/stale_labeler.yml

- Reduce the text bloat.
- Make labels a bit more intuitive.
- Remove all "PR" and "I" label prefixes.
- Add "Type" prefix to all conventional commit label types.
- Repair the stale labeler.
- Fix a typo in the PR template.
- Maybe add "Area" prefix.
- Expand "Status" labels.
- None.

ci: Overhaul label names and adjust release notes

---

scripts/scr_add_item/scr_add_item.gml
scripts/scr_destroy_planet/scr_destroy_planet.gml

style: scr_destroy_planet and scr_add_item

---

scripts/scr_add_artifact/scr_add_artifact.gml

style: scr_add_artifact.gml

---

scripts/scr_add_artifact/scr_add_artifact.gml

- Fix a bug, due to `ship_id` method not being called when used as the array index.
- Nothing.
- https://discord.com/channels/714022226810372107/1358283928506601664

fix: Artifact destroying crash

---

scripts/scr_unit_equip_functions/scr_unit_equip_functions.gml

- Fix a bug with mobility artifacts behaving funny and crashing the game.
- Make the artifact equip related logic more robust.
- Artifact ID and name are used separately now, preventing the risk of trying to access the array by a string.
- Style the code, because sorry.
- These functions are bad and require merging, as 80% of the code is the same.
- Equipping/unequipping artifact items and normal items. Don't see any issues.
- Bug report: https://discord.com/channels/714022226810372107/1357311198218948688

refactor: Equipment update function artifact equip robustness

---

ChapterMaster.yyp
objects/obj_creation/Step_0.gml
objects/obj_ini/Create_0.gml
scripts/scr_apothecary_ground/scr_apothecary_ground.gml
scripts/scr_chapter_new/scr_chapter_new.gml
scripts/scr_chapter_random/scr_chapter_random.gml
scripts/scr_complex_colour_kit/scr_complex_colour_kit.gml
scripts/scr_creation/scr_creation.gml
scripts/scr_initialize_custom/scr_initialize_custom.gml
scripts/scr_livery_setup/scr_livery_setup.gml
scripts/scr_marine_struct/scr_marine_struct.gml
scripts/scr_mission_functions/scr_mission_functions.gml
scripts/scr_squads/scr_squads.gml
scripts/scr_struct_functions/scr_struct_functions.gml
scripts/scr_struct_functions/scr_struct_functions.yy
scripts/scr_unit_traits/scr_unit_traits.gml

- Use the built-in function, that is likely more efficient and simple.
- Add a way to check if a struct is empty.
- Replace all uses of `DeepCloneStruct()` with `variable_clone()`.
- Add a new function `struct_empty()`.
- Nothing.
- Launched the game, custom chapter, save, load - no issues. Pre-made chapters, save, load - no issues.
- None.

refactor: Deprecate DeepCloneStruct; Add struct_empty()

---

.github/workflows/release_dev.yml

ci: Fix dev release workflow

---

objects/obj_controller/Create_0.gml
scripts/scr_load/scr_load.gml

- Nothing.
- Loaded in as imperial fists, queued up a few things with different quantities, checked numbers, saved, loaded immediately, looked good, exit to main menu, loaded from main menu, also looked good.
- https://discord.com/channels/714022226810372107/1359393197377327225

fix: forge queue and i assume apothecary points being broke on save/load

---

objects/obj_ini/Create_0.gml

- Nothing.
- save loaded once and they stayed, so i assume thats fixed
- https://discord.com/channels/714022226810372107/1359536645128589322.

fix: Test-Slave Incubators save/loading

---

.github/workflows/gamemaker_build.yml

ci: Manual gamemaker build for testing

---

scripts/scr_initialize_custom/scr_initialize_custom.gml

- Nothing.
- Loaded a fresh game of obliterated, strength 5 and no other traits, screenshot is the result
- https://discord.com/channels/714022226810372107/1362091154270720244

fix: Obliterated generating a 1st company

---

.github/workflows/release_dev.yml

ci: Test 10 date tags

---

.github/workflows/release_dev.yml
.github/workflows/release_stable.yml

ci: Nightly build and other improvements/fixes

---

scripts/scr_complex_colour_kit/scr_complex_colour_kit.gml

- Fix a crash.
- Fix typo passing arguments where not needed.
- Nothing.
- Bug report: https://discord.com/channels/714022226810372107/1363645776672063638

fix: Colour pick click detection typo

---

.github/workflows/release_dev.yml

ci: It was not matching the wildcard

---

scripts/scr_ComplexSet/scr_ComplexSet.gml
scripts/scr_draw_unit_image/scr_draw_unit_image.gml

- Ensure all surfaces are cleared before freeing from memory
- Nothing.
- None.

fix: Clear the surfaces before freeing

---

.github/workflows/release_dev.yml

ci: Check all commit types since last release

---

scripts/NameGenerator/NameGenerator.gml

- There is some kind of weird error happening in this return and I want to catch it.
- More info about the return values in the log message.
- Nothing.
- Bug report: https://discord.com/channels/714022226810372107/1365501015628972152

chore: More logging for the NameGenerator

---

.github/workflows/release_dev.yml
.github/workflows/stale_labeler.yml

- Hopefully avoid github peak load hours.
- Move all cron triggers two hours back.
- Nothing.
- None.

ci: Run daily workflows at 22:00 UTC

---

options/main/options_main.yy

- Fix the chapter composition breakage on save/load.
- Figure out what is actually causing this and fix it.
- Saved and loaded.
- Bug: https://discord.com/channels/714022226810372107/1366840002704834650

revert: Copy-on-Write back to true

---

scripts/scr_inquisition_mission/scr_inquisition_mission.gml

- Nothing.
-  fixes https://discord.com/channels/714022226810372107/1366974010403061851/1366974010403061851
-

fix: Crash on mission_inquisition_tyranid_organism 

---

objects/obj_controller/Create_0.gml

- Maybe fix a bug.
- Nothing.
- Bug report: https://discord.com/channels/714022226810372107/1366997125069799434

refactor: Inquisitor, loyalty, quest arrays with array_create()

---

.github/workflows/release_dev.yml

ci: Add debugging to old release deletion

---

scripts/scr_initialize_custom/scr_initialize_custom.gml

- Nothing.
-  https://discord.com/channels/714022226810372107/1367979269799805059

fix: Elite guard trait not working

---

.github/workflows/release_dev.yml

ci: Attempt to fix commit checking and old build deletion

---

objects/obj_controller/Create_0.gml
objects/obj_creation/Create_0.gml
objects/obj_creation/Draw_0.gml
objects/obj_creation/Step_0.gml
objects/obj_ncombat/Alarm_1.gml
scripts/scr_creation/scr_creation.gml
scripts/scr_creation_draw_slides/scr_creation_draw_slides.gml
scripts/scr_creation_home_planet_create/scr_creation_home_planet_create.gml
scripts/scr_initialize_custom/scr_initialize_custom.gml
scripts/scr_livery_setup/scr_livery_setup.gml
scripts/scr_load_controller/scr_load_controller.gml
scripts/scr_powers/scr_powers.gml
scripts/scr_restart_variables/scr_restart_variables.gml
scripts/scr_system_spawn_functions/scr_system_spawn_functions.gml
scripts/scr_ui_settings/scr_ui_settings.gml

- Readability.
- Fixing a bug.
- The enum part is self-descriptive.
- The fix is replacing two blocks of code in init_custom with one. Not sure why you needed two.
- Nothing.
- Launched the game as a custom, no progenitor chapter to check if the str bug is fixed - it is.
- Bug report: https://discord.com/channels/714022226810372107/1368836502489927721

refactor: eCHAPTER_TYPE enum and str slider fix

---

objects/obj_controller/Create_0.gml
scripts/scr_array_functions/scr_array_functions.gml
scripts/scr_ui_manage/scr_ui_manage.gml

- Maybe fix a bug.
- Fix the array initialization to be sane and let the IDE know about it.
- Make the code a tiny bit more readable.
- Initialize temp array with `array_create` and (new) `array_set_range`, and fix a weird use of `i` in a `t` based loop.
- Assign `temp[120]` (selected unit) to a local var where it's used.
- Replace a weird `cn` var with just using the full object name.
- Add `obj_controller` accessor where temp vars are used to explicitly tell where they are coming from, as otherwise IDE doesn't like them.
- Nothing.
- I HAVEN'T TESTED THIS, BECAUSE I CAN'T ATM!
- Bug report: https://discord.com/channels/714022226810372107/1371540899649290492

refactor: obj_controller and ui_manage temp array stuff

---

.github/workflows/release_dev.yml

ci: Debug the old release deletion again

---

objects/obj_ncombat/Alarm_2.gml
objects/obj_saveload/Create_0.gml
objects/obj_saveload/Draw_0.gml
objects/obj_saveload/Mouse_60.gml

- fixes the "Unknown Chapter" stuff
- also fixes scroll up to show the autosave slot again
- an hour of work to figure out an off-by-1 error 
- Nothing.
- loading from main menu, loading from ingame, saving in game, deleting saves.
- did you know you can have save1.json save2.json save3.json save4.json, then delete save3.json and the thing just keeps working? i dont want to know how 
-  https://discord.com/channels/714022226810372107/1372735068698579044

fix: Saveload screen fixed

---

scripts/scr_initialize_custom/scr_initialize_custom.gml

fix: Extra ships not applying to custom chaps

---

docs/CODE_STYLE.md

docs: Update CODE_STYLE.md

---

scripts/scr_chapter_random/scr_chapter_random.gml

style: Format scr_chapter_random, argument name change

---

objects/obj_ground_mission/Alarm_6.gml

style: Format obj_ground_mission alarm_6

---

scripts/scr_return_ship/scr_return_ship.gml

style: Format scr_return_ship

---

.github/workflows/gamemaker_build.yml

ci: Bump igor-setup version

---

scripts/scr_ui_settings/scr_ui_settings.gml

style: Format scr_ui_settings

---

scripts/scr_initialize_custom/scr_initialize_custom.gml

- Fix a bug.
- Remove the chapter type check, preventing the related part of code from working with the premade chapters.
- Nothing.
- New game as lamenters to check if their STR value works.
- Bug report: https://discord.com/channels/714022226810372107/1375726495179477043

fix: Chapter strength values for pre-made chapters

---

objects/obj_saveload/Draw_0.gml

- It doesn't work and crashes the game.
- Nothing.
- None.

fix: Disable the "Restart" save button

---

scripts/scr_turn_first/scr_turn_first.gml

- Fix a bug.
- Fixed some syntax issues and ensured that there is no var overshadowing.
- Nothing.
- Checked that the bug is gone.
- Bug report: https://discord.com/channels/714022226810372107/1378110279308541982

fix: scr_turn_first crash

---

scripts/scr_star_ownership/scr_star_ownership.gml

fix: Dead planet ownership defaulting to orks

---

.github/workflows/release_dev.yml

ci: Enable old dev release deletion

---

objects/obj_ground_mission/Alarm_6.gml

- Nothing.
- Tested a save with the issue.
- Bug report: https://discord.com/channels/714022226810372107/1385532547479507024

fix: Remove STC from the planet after sending it to Admech

---

scripts/scr_weapon/scr_weapon.gml

- Return the deleted Storm Shield.
- Fix broken indentation.
- https://canary.discord.com/channels/714022226810372107/1389354966497624174

fix: The return of the Storm Shield

---

objects/obj_garbage_collector/Step_0.gml

- https://discord.com/channels/714022226810372107/714023282780799028/1393092840380432506

fix: Revert garbage collector delay

---

.github/workflows/release_dev.yml

ci: Maybe setup discord release notifications

---

.github/workflows/discord-prerelease-notification.yml

ci: Maybe published trigger will work

---

.github/workflows/discord-prerelease-notification.yml
.github/workflows/release_dev.yml

ci: Here we go again

---

.github/workflows/discord-prerelease-notification.yml
.github/workflows/release_dev.yml

ci: Attempt 99 at fixing release notifications

---

scripts/scr_draw_management_unit/scr_draw_management_unit.gml

- Open chapter management.
- https://canary.discord.com/channels/714022226810372107/1395205094848466964

fix: Chapter management crash

---

.github/workflows/release_stable.yml

ci: release_stable workflow fixing

---

.github/workflows/gamemaker_build.yml

ci: More fixing to the stable-release workflow

---

docs/README.md

docs: Add contributor avatar list to README

---

docs/README.md

docs: Update the 1d6ch wiki link
